services:
  db:
    image: postgres:15-alpine
    container_name: gvw-postgres
    restart: always
    environment:
      POSTGRES_USER: gvw
      POSTGRES_PASSWORD: gvw
      POSTGRES_DB: gvw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
